### ISSUE TITLE
verusd compiled with gcc 8 crashing

### ISSUE THREAD

**Issue by cipig** [VerusCoin/VerusCoin#249]
verusd is crashing after start when compiled with gcc 8
```
[Nov15 16:22] verusd[25995]: segfault at 14eca ip 00007f546891465f sp 00007fff2942b060 error 4 in libgcc_s.so.1[7f5468906000+11000]
[  +0.000163] Code: 70 fe ff ff 0f 29 9d 00 ff ff ff 66 0f 6f 95 80 fe ff ff 66 0f 6f 9d 90 fe ff ff 0f 29 a5 10 ff ff ff 66 0f 6f a5 a0 fe ff ff <48> 83 7b 10 00 0f 29 ad 20 ff ff ff 66 0f 6f ad b0 fe ff ff 0f 29
```
Problem is, that gcc 5 was removed from debian a long time ago.

**Comment by DeckerSU** [comment]
this https://github.com/VerusCoin/VerusCoin/pull/255 should solve it.

**Comment by cipig** [comment]
I still have a segfault, this time with backtrace
```
#0  __GI___libc_free (mem=0xbe7ef3d0076f8405) at malloc.c:3093
#1  0x000055555576c5fd in prevector<28u, unsigned char, unsigned int, int>::~prevector (this=0x7ffeec041dc8, __in_chrg=<optimized out>) at /usr/include/c++/8/ext/new_allocator.h:116
#2  CScript::~CScript (this=0x7ffeec041dc8, __in_chrg=<optimized out>) at ./script/script.h:477
#3  CTxOut::~CTxOut (this=0x7ffeec041dc0, __in_chrg=<optimized out>) at ./primitives/transaction.h:430
#4  std::_Destroy<CTxOut> (__pointer=0x7ffeec041dc0) at /usr/include/c++/8/bits/stl_construct.h:98
#5  std::_Destroy_aux<false>::__destroy<CTxOut*> (__last=<optimized out>, __first=0x7ffeec041dc0) at /usr/include/c++/8/bits/stl_construct.h:108
#6  std::_Destroy<CTxOut*> (__last=<optimized out>, __first=<optimized out>) at /usr/include/c++/8/bits/stl_construct.h:137
#7  std::_Destroy<CTxOut*, CTxOut> (__last=0x7ffeec041e20, __first=<optimized out>) at /usr/include/c++/8/bits/stl_construct.h:206
#8  std::vector<CTxOut, std::allocator<CTxOut> >::~vector (this=0x7fff027f8cf8, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_vector.h:567
#9  CTransaction::~CTransaction (this=0x7fff027f8cb0, __in_chrg=<optimized out>) at ./primitives/transaction.h:522
#10 0x0000555555620870 in CTxHolder::~CTxHolder (this=0x7fff027f8c88, __in_chrg=<optimized out>) at ./cheatcatcher.h:25
#11 std::pair<unsigned int const, CTxHolder>::~pair (this=0x7fff027f8c80, __in_chrg=<optimized out>) at /usr/include/c++/8/bits/stl_pair.h:208
#12 CCheatList::Add (this=0x5555566314e0 <cheatList>, txh=...) at cheatcatcher.cpp:134
#13 0x000055555573f808 in DisconnectTip (state=..., chainparams=..., fBare=<optimized out>) at main.cpp:4186
#14 0x000055555573fea2 in ActivateBestChainStep (pblock=<optimized out>, pindexMostWork=<optimized out>, chainparams=..., state=...) at main.cpp:4439
#15 ActivateBestChain (state=..., chainparams=..., pblock=<optimized out>) at main.cpp:4541
#16 0x00005555557434e2 in ProcessNewBlock (state=..., chainparams=..., pfrom=0x7ffee8030250, pblock=0x7fff027fab20, fForceProcessing=<optimized out>, dbp=0x0, height=0, from_miner=false) at sync.h:64
#17 0x000055555574941e in ProcessMessage (pfrom=0x7ffee8030250, strCommand="block", vRecv=..., nTimeReceived=<optimized out>) at main.cpp:7806
#18 0x000055555574aded in ProcessMessages (pfrom=0x7ffee8030250) at /usr/include/c++/8/bits/basic_string.h:936
#19 0x00005555557d22a3 in boost::function1<bool, CNode*>::operator() (a0=<optimized out>, this=<optimized out>) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/function/function_template.hpp:677
#20 boost::signals2::detail::call_with_tuple_args<bool>::m_invoke<boost::function<bool (CNode*)>, 0u, CNode*&>(boost::function<bool (CNode*)>&, boost::signals2::detail::unsigned_meta_array<0u>, std::tuple<CNode*&> const&, boost::disable_if<boost::is_void<boost::function<bool (CNode*)>::result_type>, void>::type*) const (this=<optimized out>, args=std::tuple containing = {...}, func=...) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:98
#21 boost::signals2::detail::call_with_tuple_args<bool>::operator()<boost::function<bool (CNode*)>, CNode*&, 1ul>(boost::function<bool (CNode*)>&, std::tuple<CNode*&> const&, mpl_::size_t<1ul>) const (this=<optimized out>, args=std::tuple containing = {...}, func=...)
    at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:90
#22 boost::signals2::detail::variadic_slot_invoker<bool, CNode*>::operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >(boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > const&) const (connectionBody=..., 
    this=0x7fff027fb880) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:133
#23 boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >::dereference() const (this=0x7fff027fb440) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/slot_call_iterator.hpp:110
#24 boost::iterators::iterator_core_access::dereference<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > const&) (f=...) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/iterator/iterator_facade.hpp:550
#25 boost::iterators::detail::iterator_facade_base<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >, bool, boost::iterators::single_pass_traversal_tag, bool const&, long, false, false>::operator*() const (this=0x7fff027fb440) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/iterator/iterator_facade.hpp:656
#26 CombinerAll::operator()<boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >(boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >) const (this=<optimized out>, first=..., last=...) at net.h:92
#27 boost::signals2::detail::combiner_invoker<bool>::operator()<CombinerAll, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >(CombinerAll&, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >, boost::signals2::detail::slot_call_iterator_t<boost::signals2::detail::variadic_slot_invoker<bool, CNode*>, std::_List_iterator<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> > >, boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool (CNode*), boost::function<bool (CNode*)> >, boost::signals2::mutex> >) const (this=<optimized out>, combiner=..., first=..., last=...) at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/result_type_wrapper.hpp:53
#28 boost::signals2::detail::signal_impl<bool (CNode*), CombinerAll, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) (args#0=<optimized out>, this=0x555556c2f520)
    at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/signal_template.hpp:243
#29 boost::signals2::signal<bool (CNode*), CombinerAll, int, std::less<int>, boost::function<bool (CNode*)>, boost::function<bool (boost::signals2::connection const&, CNode*)>, boost::signals2::mutex>::operator()(CNode*) (this=0x555556603c58 <g_signals+24>, args#0=0x7ffee8030250)
    at /home/flow/wallets/VerusCoin/depends/x86_64-unknown-linux-gnu/share/../include/boost/signals2/detail/signal_template.hpp:722
#30 ThreadMessageHandler () at net.cpp:1597
#31 0x00005555556b6a38 in TraceThread<void (*)()> (name=<optimized out>, func=0x5555557d19c0 <ThreadMessageHandler()>) at /usr/include/c++/8/bits/basic_string.h:2290
#32 0x0000555555ce6e07 in thread_proxy ()
#33 0x00007ffff7d95fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#34 0x00007ffff7ae14cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by cipig** [comment]
here is another one, from a different node
```
#0  CBlock::CBlock (this=0x7fff3dff9fa8) at ./primitives/block.h:364
#1  CPBaaSMergeMinedChainData::CPBaaSMergeMinedChainData (this=0x7fff3dff9e38) at ./pbaas/pbaas.h:544
#2  std::pair<uint160 const, CPBaaSMergeMinedChainData>::pair (this=0x7fff3dff9e20) at /usr/include/c++/8/bits/stl_pair.h:303
#3  CConnectedChains::PruneOldChains (this=0x555556604f60 <ConnectedChains>, pruneBefore=1576751116) at pbaas/pbaas.cpp:794
#4  0x0000555555814c45 in CConnectedChains::SubmissionThread (this=<optimized out>) at pbaas/pbaas.cpp:1449
#5  0x0000555555ce7497 in thread_proxy ()
#6  0x00007ffff7d98fa3 in start_thread (arg=<optimized out>) at pthread_create.c:486
#7  0x00007ffff7ae44cf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

**Comment by DeckerSU** [comment]
@cipig are you sure you are running on updated daemon? 0.6.0-5?

**Comment by DeckerSU** [comment]
Can confirm crash after DisconnectTip:

```
#0  __GI___libc_free (mem=0xfc07ee702bc30c62) at malloc.c:3093
#1  0x000055555576c5ad in prevector<28u, unsigned char, unsigned int, int>::~prevector (this=0x7fff3a14ba68, 
    __in_chrg=<optimized out>) at /usr/include/c++/8/ext/new_allocator.h:116
#2  CScript::~CScript (this=0x7fff3a14ba68, __in_chrg=<optimized out>) at ./script/script.h:477
#3  CTxOut::~CTxOut (this=0x7fff3a14ba60, __in_chrg=<optimized out>) at ./primitives/transaction.h:430
#4  std::_Destroy<CTxOut> (__pointer=0x7fff3a14ba60) at /usr/include/c++/8/bits/stl_construct.h:98
#5  std::_Destroy_aux<false>::__destroy<CTxOut*> (__last=<optimized out>, __first=0x7fff3a14ba60)
    at /usr/include/c++/8/bits/stl_construct.h:108
#6  std::_Destroy<CTxOut*> (__last=<optimized out>, __first=<optimized out>)
    at /usr/include/c++/8/bits/stl_construct.h:137
#7  std::_Destroy<CTxOut*, CTxOut> (__last=0x7fff3a14bac0, __first=<optimized out>)
    at /usr/include/c++/8/bits/stl_construct.h:206
#8  std::vector<CTxOut, std::allocator<CTxOut> >::~vector (this=0x7fff537facf8, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/stl_vector.h:567
#9  CTransaction::~CTransaction (this=0x7fff537facb0, __in_chrg=<optimized out>) at ./primitives/transaction.h:522
#10 0x0000555555620870 in CTxHolder::~CTxHolder (this=0x7fff537fac88, __in_chrg=<optimized out>) at ./cheatcatcher.h:25
#11 std::pair<unsigned int const, CTxHolder>::~pair (this=0x7fff537fac80, __in_chrg=<optimized out>)
    at /usr/include/c++/8/bits/stl_pair.h:208
#12 CCheatList::Add (this=0x5555566314e0 <cheatList>, txh=...) at cheatcatcher.cpp:134
#13 0x000055555573f7b8 in DisconnectTip (state=..., chainparams=..., fBare=<optimized out>) at main.cpp:4186
#14 0x000055555573fe52 in ActivateBestChainStep (pblock=<optimized out>, pindexMostWork=<optimized out>, 
    chainparams=..., state=...) at main.cpp:4439
#15 ActivateBestChain (state=..., chainparams=..., pblock=<optimized out>) at main.cpp:4541
```

**Comment by DeckerSU** [comment]
Fixed in https://github.com/VerusCoin/VerusCoin/pull/261 .

**Comment by cipig** [comment]
Thanks. It works now with gcc-8.
